name: Build and Release .NET App

on:
  push:
    tags:
      - 'v*'  # Запускается при пуше тега v1.0.0 и т.п.

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # Укажи нужную версию

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Release
        run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -o out

      - name: Archive executable
        run: Compress-Archive -Path ./out/* -DestinationPath yt_downloader.zip

      - name: Upload Release Artifact
        uses: softprops/action-gh-release@v2
        with:
          files: yt_downloader.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
